#version 450

struct ParticleType
{
	vec2 pos;
	vec2 vel;
};

layout(std140, binding = 0) buffer ParticleSSBOOut {
   ParticleType Particles[];
};

layout(push_constant) uniform PushConsts {
	vec2 MousePosition;
	float DeltaTime;
}consts;

layout (local_size_x = 1) in;

void main()
{
	vec2 mPos = consts.MousePosition;
	mPos -= 0.5f;
	mPos *= 2.0f;

	float dTime = consts.DeltaTime;

	uint index = gl_GlobalInvocationID.x;
	vec2 pos = Particles[index].pos;
	vec2 vel = Particles[index].vel;

	vec2 diff = mPos - pos;
	float dist = distance(mPos,pos);
	diff = normalize(diff);

	if (dist > 0.05f)
	{
		float closer = 1.0f / dist;
		vel += diff*dTime*closer;
	}

	Particles[index].vel = vel;
}
