#version 450

struct ParticleType
{
	vec2 pos;
	vec2 vel;
};

layout(std140, binding = 0) buffer ParticleSSBOOut {
   ParticleType Particles[];
};

layout(push_constant) uniform PushConsts {
	float DeltaTime;
}consts;

layout (local_size_x = 1) in;

void main()
{
	float dTime = consts.DeltaTime;

	uint index = gl_GlobalInvocationID.x;
	vec2 pos = Particles[index].pos;
	vec2 vel = Particles[index].vel;

	if (pos.x >= 1.0f && vel.x >= 0.0f)
			vel.x *= -1.0;
	if (pos.x <= -1.0f && vel.x <= 0.0f)
			vel.x *= -1.0f;
	if (pos.y >= 1.0f && vel.y >= 0.0f)
			vel.y *= -1.0f;
	if (pos.y <= -1.0f && vel.y <= 0.0f)
			vel.y *= -1.0f;

	pos += vel*dTime;

	vel -= vel *(0.6f*dTime);


	Particles[index].pos = pos;
	Particles[index].vel = vel;
}
